import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NOX MOTORSPORT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link
          href="https://fonts.cdnfonts.com/css/stretch-pro"
          rel="stylesheet"
        />
      </Head>
      <main className=" bg-[#141414] after:bg-[url('/img/9793.jpg')] after:h-screen after:w-screen after:absolute after:z-[0] after:opacity-50 h-screen gap-6 flex justify-center items-center flex-col px-10 after:bg-[5%] after:bg-repeat after:bg-contain">
        <div className="flex flex-col items-center gap-7 justify-center z-[1] after:bg-gradient-to-tr after:from-purple-500/10 after:h-screen after:w-screen after:absolute">
          <Image
            src="/img/logo-clean.svg"
            alt="Nox Logo"
            width={500}
            height={24}
            priority
          />
          <h1 className="text-3xl font-bold text-white">Em construção...</h1>
        </div>
      </main>
    </>
  );
}
